trigger:
  branches:
    include:
    - master
  paths:
    include:
    - k8s_cd/deployment_config/deploy.json
    - k8s_cd/kubernetes_config/*
    exclude:
    - k8s_cd/kubernetes_config/cic_helm/*
    

pool: amey-vmpool

stages:
- stage:
  jobs:
  - job: Deploy
    displayName: Guestbook Application Deployment
    pool: amey-vmpool
    steps:
    
    - task: Bash@3
      inputs:
        targetType: 'inline'
        script: |
          sudo apt-get install python -y
          sudo apt-get install unzip -y
      displayName: 'Installing Unzip packge'
    
    - task: KubectlInstaller@0
      inputs:
        kubectlVersion: 'latest'
      displayName: 'Installing kubectl'

    - task: PythonScript@0
      displayName: 'Reading configuration file'
      inputs:
        scriptSource: 'filePath'
        scriptPath: '$(System.DefaultWorkingDirectory)/ci_cd/pipeline_config/read_config.py'
        arguments: --config_file $(System.DefaultWorkingDirectory)/k8s_cd/deployment_config/deploy.json --action 'apply'
    - task: Kubernetes@0
      displayName: 'Deploy Guestbook Application'
      inputs:
        kubernetesServiceConnection: 'bharathi-cn-svc-con'
        command: apply
        useConfigurationFile: true
        configuration: '$(System.DefaultWorkingDirectory)/$(K8S_CONFIG_PATH)'
